// ****** mission.js ******

// Define Mission Types using a constant object for better readability and safety
const MISSION_TYPE = {
    DELIVERY_LEGAL: 'Legal delivery',
    DELIVERY_ILLEGAL: 'Illegal delivery',
    BOUNTY_PIRATE: 'Bounty',
    BOUNTY_POLICE: 'Bounty',
    BOUNTY_ALIEN: 'Alien Bounty', // Add this new type
    ASSASSINATION: 'Assassination', // Named-target assassination
    SABOTAGE: 'Sabotage' // Destroy a specific space object near a planet
    //ASSASSINATION_CLEAN: 'Official Assassination',
    //ASSASSINATION_WANTED: 'Political Assassination',
    //COURIER: 'Courier (Highspeed Delivery)',
    //MINING: 'Mining Contract',
    //RESCUE: 'Search and Rescue',
    //CLEARANCE: '',
    //ESCORT: 'Escort Mission',
    //EXPLORATION: 'Exploration'
};

class Mission {
    /**
     * Represents an available or active mission.
     * Can be initialized from a configuration object generated by MissionGenerator,
     * or rehydrated from saved data object loaded from localStorage.
     * @param {object} data - Configuration object OR loaded save data object. It should contain properties matching the class fields.
     */
    constructor(data = {}) {
        // Handle ID: Start with data.id, then try positional arg if legacy (not likely here), else auto-gen
        if (data.id) {
            this.id = data.id;
        } else {
            // If no ID provided, auto-increment
            this.id = Mission.nextId++;
        }

        this.title = data.title || 'Unknown Mission';
        this.type = data.type || MISSION_TYPE.DELIVERY_LEGAL;
        this.description = data.description || '';

        // --- Location Data ---
        this.originSystem = data.originSystem || 'Unknown';
        this.originStation = data.originStation || 'Unknown';
        this.destinationSystem = data.destinationSystem || 'Unknown';
        this.destinationStation = data.destinationStation || 'Unknown';
        this.destinationSystemIndex = data.destinationSystemIndex; // Optional optimization

        // --- Specific Mission Data ---
        this.targetCount = data.targetCount || 0; // For Bounty/Kill missions
        this.targetName = data.targetName || null; // For Assassination/specific targets
        this.targetShipType = data.targetShipType || null;
        this.guardCount = data.guardCount || 0;
        this.guardShipType = data.guardShipType || null;

        this.cargoType = data.cargoType || null;   // For delivery
        this.cargoQuantity = data.cargoQuantity || 0;  // Amount of cargo for delivery

        // --- Rewards & Penalties ---
        this.rewardCredits = data.rewardCredits || data.reward || 0; // Credits awarded on completion (accept 'reward' alias)
        this.isIllegal = data.isIllegal || false; // Flag for illegal missions (smuggling, etc.)
        this.requiredRep = data.requiredRep || 0;    // Placeholder for reputation needed later
        this.timeLimit = data.timeLimit || null;    // Placeholder for time limit later (e.g., seconds)

        // --- Assassination-specific fields ---
        // `targetName`: human-readable name of the individual to eliminate
        // `targetShipType`: ship type the target will be traveling in (key from `SHIP_DEFINITIONS`)
        // `canLeaveSystem`: whether the target may leave the system (if true, mission cancels on exit)
        this.targetName = data.targetName || null;
        this.targetShipType = data.targetShipType || null;
        this.canLeaveSystem = data.canLeaveSystem || false;
        this.guardCount = data.guardCount || 0;
        this.guardShipType = data.guardShipType || null;
        // runtime reference to the spawned enemy (if spawned)
        // Keep runtime enemy reference non-enumerable so save/clone operations don't include large objects
        Object.defineProperty(this, '_targetEnemyRef', { value: null, writable: true, enumerable: false, configurable: true });
        this._targetEnemyId = data._targetEnemyId || null;
        // runtime guard tracking (non-enumerable): arrays of guard objects and guard ids
        Object.defineProperty(this, '_guardRefs', { value: [], writable: true, enumerable: false, configurable: true });
        this._guardIds = data._guardIds || [];

        // --- Sabotage-specific fields ---
        // `offeringFaction`: who offers the mission (e.g., 'Separatist','Imperial','Military')
        // `targetFaction`: faction that owns/values the object to be destroyed (derived if not provided)
        // `targetObjectType`: human readable type of the object to destroy (e.g., 'Communication Relay', 'Fuel Array')
        // `targetObjectId`: persisted id of the specific object if available (optional)
        // `targetPlanetName`: the planet near which the object is located
        this.offeringFaction = data.offeringFaction || null;
        this.targetFaction = data.targetFaction || null;
        this.targetObjectType = data.targetObjectType || null;
        this.targetObjectId = data.targetObjectId || null;
        this.targetPlanetName = data.targetPlanetName || null;
        // Persist the system index where the target object lives (if provided)
        // This helps resolve targets that live in other systems when the player
        // is not currently present — we can ensure the remote system spawns
        // its decorative objects so the persisted id remains valid.
        this.spawnSystemIndex = (typeof data.spawnSystemIndex === 'number') ? data.spawnSystemIndex : (typeof data.systemIndex === 'number' ? data.systemIndex : null);

        // --- Tracking Properties ---
        // Initialize status and progress from saved data if present, otherwise use defaults for a new mission
        this.status = data.status || 'Available'; // 'Available', 'Active', 'Completable', 'Completed', 'Failed'
        this.progressCount = data.progressCount || 0; // e.g., number of pirates killed so far

        // Optional log to trace object creation/rehydration
        console.log(`Mission object created/rehydrated: ID=${this.id.toString().slice(-5)}, Title=${this.title}, Status=${this.status}, Progress=${this.progressCount}, TargetName=${this.targetName}`);

        // If this is a sabotage mission and no description provided, generate a flavored backstory
        if (this.type === MISSION_TYPE.SABOTAGE && (!data.description || data.description === 'No description provided.')) {
            this.description = this._generateSabotageBackstory();
        }

        // Ensure sabotage missions carry very high rewards by default
        if (this.type === MISSION_TYPE.SABOTAGE) {
            if (data.rewardCredits != null) {
                this.rewardCredits = data.rewardCredits;
            } else {
                // Default large reward; allow later override when mission generated
                this.rewardCredits = 100000; // 100k credits baseline
            }
        }
    }

    /** Sets the mission status to 'Active'. Called by Player.acceptMission. */
    activate() {
        MISSION_LOG(`      >>> Mission.activate() called for: ${this.title}`); // Log entry
        if (this.status === 'Available') { // Only activate if it was available
            this.status = 'Active';
            MISSION_LOG(`      <<< Mission status set to: ${this.status}`); // Log exit
        } else {
            console.warn(`Mission.activate() called on mission with status ${this.status}. Should be 'Available'.`);
        }

        // Special handling for delivery missions: add cargo to player's ship
        try {
            if ((this.type === MISSION_TYPE.DELIVERY_LEGAL || this.type === MISSION_TYPE.DELIVERY_ILLEGAL) &&
                this.cargoType && this.cargoQuantity > 0 &&
                typeof player !== 'undefined' && player) {
                // Check if player has enough cargo space
                const usedSpace = player.cargo.reduce((sum, item) => sum + item.quantity, 0);
                const availableSpace = player.cargoCapacity - usedSpace;

                if (availableSpace >= this.cargoQuantity) {
                    // Add cargo to player's ship
                    const existingItem = player.cargo.find(item => item.name === this.cargoType);
                    if (existingItem) {
                        existingItem.quantity += this.cargoQuantity;
                    } else {
                        player.cargo.push({ name: this.cargoType, quantity: this.cargoQuantity });
                    }
                    MISSION_LOG(`Added ${this.cargoQuantity}t ${this.cargoType} to player cargo`);
                    if (typeof uiManager !== 'undefined') {
                        uiManager.addMessage(`Loaded ${this.cargoQuantity}t ${this.cargoType} into cargo hold`);
                    }
                } else {
                    // Not enough cargo space - prevent mission acceptance
                    console.warn(`Not enough cargo space for mission! Need ${this.cargoQuantity}t, have ${availableSpace}t available`);
                    if (typeof uiManager !== 'undefined') {
                        uiManager.addMessage(`Insufficient cargo space! Need ${this.cargoQuantity}t, have ${availableSpace}t available`, [255, 100, 100]);
                    }
                    this.status = 'Available'; // Revert status
                    return false; // Signal failure
                }
            }
        } catch (e) {
            console.error('Mission.activate (delivery cargo) failed:', e);
            this.status = 'Available'; // Revert on error
            return false;
        }

        // Special handling for assassination missions: spawn the named target near the player
        try {
            if (this.type === MISSION_TYPE.ASSASSINATION && typeof player !== 'undefined' && player && player.currentSystem) {
                // Only spawn if not already spawned
                if (!this._targetEnemyRef) {
                    const sys = player.currentSystem;
                    const angle = random(TWO_PI);
                    const spawnDist = sys._getDiagonalDistance ? sys._getDiagonalDistance() + random(150, 400) : (500 + random(150, 400));
                    const spawnX = player.pos.x + cos(angle) * spawnDist;
                    const spawnY = player.pos.y + sin(angle) * spawnDist;
                    // Choose ship type fallback
                    let shipType = this.targetShipType || (typeof PIRATE_SHIP_TYPES !== 'undefined' ? random(PIRATE_SHIP_TYPES) : 'Krait');
                    // Default role: use COMBAT so target may defend themselves
                    const role = (typeof AI_ROLE !== 'undefined') ? (AI_ROLE.COMBAT) : 'COMBAT';
                    const newEnemy = new Enemy(spawnX, spawnY, player, shipType, role);
                    newEnemy.calculateRadianProperties && newEnemy.calculateRadianProperties();
                    newEnemy.initializeColors && newEnemy.initializeColors();
                    // Set the display name if provided
                    if (this.targetName) newEnemy.displayName = this.targetName;
                    // Mark as a named assassination target for later checks
                    newEnemy.isAssassinationTarget = true;
                    // Add to system
                    sys.addEnemy(newEnemy);
                    // Spawn guards if mission requests them (guardCount provided by generator)
                    try {
                        let guardCount = this.guardCount || 1;
                        const guardShipType = this.guardShipType || null;
                        console.log(`Spawning ${guardCount} guards for assassination mission.`);
                        if (guardCount > 0) {
                            // ensure runtime containers exist
                            if (!this._guardRefs) Object.defineProperty(this, '_guardRefs', { value: [], writable: true, enumerable: false, configurable: true });
                            if (!Array.isArray(this._guardIds)) this._guardIds = [];
                            for (let g = 0; g < guardCount; g++) {
                                const gAngle = angle + (TWO_PI * (g + 1) / (guardCount + 1)) + random(-0.25, 0.25);
                                const gDist = spawnDist * 0.4 + random(80, 220);
                                const gx = newEnemy.pos.x + cos(gAngle) * gDist;
                                const gy = newEnemy.pos.y + sin(gAngle) * gDist;
                                const gShip = guardShipType || ((typeof COMBAT_SHIPS !== 'undefined' && COMBAT_SHIPS.length > 0) ? random(COMBAT_SHIPS) : (typeof PIRATE_SHIP_TYPES !== 'undefined' ? random(PIRATE_SHIP_TYPES) : 'Krait'));
                                const guardRole = (typeof AI_ROLE !== 'undefined') ? AI_ROLE.GUARD : 'GUARD';
                                const guardNPC = new Enemy(gx, gy, player, gShip, guardRole);
                                guardNPC.calculateRadianProperties && guardNPC.calculateRadianProperties();
                                guardNPC.initializeColors && guardNPC.initializeColors();
                                guardNPC.displayName = "Escort"; // For testing, give guards a name
                                guardNPC.isAssassinationGuard = true;
                                // Link guard to principal (the named target) so AI will guard/follow
                                guardNPC.principal = newEnemy;
                                // Set small formation offset to keep guards spaced
                                try { guardNPC.guardFormationOffset = createVector(cos(gAngle) * (80 + g * 30), sin(gAngle) * (80 + g * 30)); } catch (e) { /* createVector may be unavailable in some contexts */ }
                                // Add guard NPC to system
                                sys.addEnemy(guardNPC);
                                // Track guard refs and ids (ids are persisted, refs are runtime-only)
                                try { this._guardRefs.push(guardNPC); } catch (e) { /* ignore */ }
                                try { this._guardIds.push(guardNPC.id); } catch (e) { /* ignore */ }
                                MISSION_LOG(`  -> Spawned guard for target: ${guardNPC.shipTypeName} at (${gx.toFixed(0)},${gy.toFixed(0)})`);
                            }
                            console.log(`Spawned ${guardCount} guards successfully.`);
                            if (typeof uiManager !== 'undefined') uiManager.addMessage(`${guardCount} escort(s) detected around the target.`);
                        }
                    } catch (e) { console.warn('Failed to spawn guards for assassination mission:', e); }
                    // Store references for mission tracking
                    Object.defineProperty(this, '_targetEnemyRef', { value: newEnemy, writable: true, enumerable: false, configurable: true });
                    this._targetEnemyId = newEnemy.id;
                    MISSION_LOG(`Assassination target spawned: ${newEnemy.displayName || newEnemy.shipTypeName} (${newEnemy.id}) at (${spawnX.toFixed(0)},${spawnY.toFixed(0)})`);
                    // Notify player
                    if (typeof uiManager !== 'undefined') uiManager.addMessage(`Target spotted: ${newEnemy.displayName || newEnemy.shipTypeName}`);
                }
            }
        } catch (e) { console.error('Mission.activate (assassination) failed:', e); }
    }

    /**
     * Generate a flavorful backstory for sabotage missions when none provided.
     * Uses `offeringFaction`, `targetFaction`, `targetObjectType`, and `targetPlanetName` if available.
     */
    _generateSabotageBackstory() {
        const offer = this.offeringFaction || 'A local faction';
        // Derive a likely opposing faction if none provided
        let target = this.targetFaction;
        if (!target) {
            if (offer && offer.toLowerCase().includes('separat')) target = 'Imperial';
            else if (offer && offer.toLowerCase().includes('imper')) target = 'Separatist';
            else if (offer && offer.toLowerCase().includes('milit')) target = 'Alien';
            else target = 'a rival faction';
        }
        const obj = this.targetObjectType || 'strategic installation';
        const planet = this.targetPlanetName ? `close to ${this.targetPlanetName}` : 'in orbit of a nearby planet';

        let reason = '';
        // Create faction-aware reasons
        if (offer && offer.toLowerCase().includes('separat')) {
            reason = `The ${offer} claim the ${obj} is a forward listening post used by ${target} forces to track convoy movements and coordinate punitive strikes. Destroying it would blind the occupiers and open a window for daring raids.`;
        } else if (offer && offer.toLowerCase().includes('imper')) {
            reason = `Agents of the ${offer} have surfaced intelligence that the ${obj} is a covert separatist supply hub funneling weapons through the system. Removing it would disrupt their logistics and restore order.`;
        } else if (offer && offer.toLowerCase().includes('milit')) {
            reason = `Military analysts suspect the ${obj} has been corrupted by alien tech — its emissions are destabilizing local navigation and threatening civilian traffic. The military wants it eliminated before it spreads.`;
        } else {
            reason = `Intelligence suggests the ${obj} is a critical node for ${target}. Removing it would significantly weaken their presence in the region.`;
        }

        // Return a concise backstory only — the explicit objective/location/offering
        // fields are shown separately in `getDetails()` to avoid repetition.
        return `${reason}`;
    }

    /** Per-frame update called from Player.update to monitor special mission targets. */
    update(currentSystem) {
        if (this.status !== 'Active') return; // Only monitor active missions
        // Attempt to relink runtime references if possible (useful after load)
        try { this._ensureRuntimeLinked(currentSystem); } catch (e) { MISSION_LOG('Runtime relink failed:', e); }

        // --- Assassination monitoring ---
        if (this.type === MISSION_TYPE.ASSASSINATION) {
            // If no spawned target, nothing to monitor
            if (!this._targetEnemyRef) return;
            try {
                const enemy = this._targetEnemyRef;
                // If the enemy was destroyed -> allow completion
                if (enemy.destroyed) {
                    if (typeof player !== 'undefined' && player && player.activeMission === this) {
                        this.progressCount = Math.max(1, this.progressCount);
                        if (typeof this.complete === 'function') {
                            this.complete(player);
                            try { this._cleanupAssassinationRuntime(currentSystem); } catch (e) { MISSION_LOG('Cleanup after complete failed:', e); }
                            if (typeof player !== 'undefined' && player && player.activeMission === this) player.activeMission = null;
                        }
                    }
                    return;
                }

                // If the target left the player's current system, cancel the mission
                if (enemy.currentSystem && currentSystem && enemy.currentSystem !== currentSystem) {
                    this.fail();
                    if (typeof uiManager !== 'undefined') uiManager.addMessage(`Mission canceled: target ${enemy.displayName || enemy.shipTypeName} left the system.`, [255, 120, 80]);
                    try { this._cleanupAssassinationRuntime(currentSystem); } catch (e) { MISSION_LOG('Cleanup after fail failed:', e); }
                    if (typeof player !== 'undefined' && player && player.activeMission === this) player.activeMission = null;
                }
            } catch (e) { console.error('Mission.update (assassination) error:', e); }
            return;
        }

        // --- Sabotage monitoring ---
        if (this.type === MISSION_TYPE.SABOTAGE) {
            try {
                // Ensure we have a runtime reference to the target space object (if possible)
                if (!this._targetObjectRef && this.targetObjectId && currentSystem && Array.isArray(currentSystem.spaceObjects)) {
                    const so = currentSystem.spaceObjects.find(o => o && o.id === this.targetObjectId);
                    if (so) Object.defineProperty(this, '_targetObjectRef', { value: so, writable: true, enumerable: false, configurable: true });
                }

                const targetObj = this._targetObjectRef;
                // If we have a linked object and it was destroyed, award mission
                if (targetObj && targetObj.destroyed) {
                    // Complete the mission when the linked target object is destroyed.
                    // Don't require `player.activeMission === this` because mission
                    // instances can become detached from the player's activeMission
                    // reference (e.g. during save/load or temporary object moves).
                    try {
                        if (typeof player !== 'undefined' && player) {
                            if (typeof this.complete === 'function') this.complete(player);
                            // Clear any sabotage-specific runtime refs
                            try { Object.defineProperty(this, '_targetObjectRef', { value: null, writable: true, enumerable: false, configurable: true }); } catch (e) { this._targetObjectRef = null; }
                            // Clear player's activeMission if it still points at this mission
                            try { if (player.activeMission === this) player.activeMission = null; } catch (e) { }
                        }
                    } catch (e) { console.error('Mission.update (sabotage) completion error:', e); }
                    return;
                }

                // If we don't have a linked object but we do have a persisted id, try a galaxy-wide search
                if (!targetObj && this.targetObjectId) {
                    let foundAny = false;
                    try {
                        if (typeof galaxy !== 'undefined' && Array.isArray(galaxy.systems)) {
                            for (let si = 0; si < galaxy.systems.length; si++) {
                                const sys = galaxy.systems[si];
                                if (!sys || !Array.isArray(sys.spaceObjects)) continue;
                                const so = sys.spaceObjects.find(o => o && o.id === this.targetObjectId);
                                if (so) {
                                    // If found and destroyed -> complete
                                    foundAny = true;
                                    if (so.destroyed) {
                                        try { if (typeof this.complete === 'function') this.complete(player); } catch (e) { console.error('Error completing mission (galaxy-found destroyed):', e); }
                                        try { Object.defineProperty(this, '_targetObjectRef', { value: null, writable: true, enumerable: false, configurable: true }); } catch (e) { this._targetObjectRef = null; }
                                        try { if (player && player.activeMission === this) player.activeMission = null; } catch (e) { }
                                        return;
                                    } else {
                                        // Link to the live object so monitoring proceeds normally
                                        try { Object.defineProperty(this, '_targetObjectRef', { value: so, writable: true, enumerable: false, configurable: true }); } catch (e) { this._targetObjectRef = so; }
                                        return;
                                    }
                                }
                            }
                        }
                    } catch (e) { /* ignore galaxy search errors */ }

                    // If we didn't find the object anywhere in the galaxy, assume it was removed/destroyed
                    if (!foundAny) {
                        try {
                            if (typeof this.complete === 'function') this.complete(player);
                            try { Object.defineProperty(this, '_targetObjectRef', { value: null, writable: true, enumerable: false, configurable: true }); } catch (e) { this._targetObjectRef = null; }
                            try { if (player && player.activeMission === this) player.activeMission = null; } catch (e) { }
                        } catch (e) { console.error('Mission.update (sabotage) assumed-missing completion error:', e); }
                        return;
                    }
                }

                // If we don't have a persisted id, we can optionally try to match by proximity/name
                // (not implemented here to avoid false-positives)
            } catch (e) { console.error('Mission.update (sabotage) error:', e); }
            return;
        }
        // Other mission types are not monitored here
        return;
    }

    /**
     * Try to link runtime enemy and guard objects from saved ids when possible.
     * Safe to call frequently; will no-op when already linked.
     */
    _ensureRuntimeLinked(currentSystem) {
        if (!currentSystem) return;
        // Link target enemy if we have an id but no runtime ref
        if (!this._targetEnemyRef && this._targetEnemyId) {
            const list = currentSystem.enemies || [];
            const found = list.find(e => e && e.id === this._targetEnemyId);
            if (found) {
                Object.defineProperty(this, '_targetEnemyRef', { value: found, writable: true, enumerable: false, configurable: true });
            }
        }
        // Link guards if we have guard ids
        if (Array.isArray(this._guardIds) && this._guardIds.length > 0 && Array.isArray(this._guardRefs) && this._guardRefs.length === 0) {
            const list = currentSystem.enemies || [];
            for (let gid of this._guardIds) {
                const g = list.find(e => e && e.id === gid);
                if (g) {
                    try { this._guardRefs.push(g); } catch (e) { }
                    // Re-establish principal if missing
                    if (!g.principal && this._targetEnemyRef) g.principal = this._targetEnemyRef;
                }
            }
        }

        // Link sabotage target SpaceObject if we have a persisted id
        try {
            // If the mission carried a spawnSystemIndex (the system where the object was created),
            // try to ensure that remote system has its spaceObjects spawned so the persisted id remains valid.
            try {
                if (!this._targetObjectRef && this.targetObjectId && (typeof galaxy !== 'undefined') && typeof this.spawnSystemIndex === 'number') {
                    const remoteSys = (galaxy && Array.isArray(galaxy.systems)) ? galaxy.systems[this.spawnSystemIndex] : null;
                    if (remoteSys) {
                        if ((!Array.isArray(remoteSys.spaceObjects) || remoteSys.spaceObjects.length === 0) && typeof remoteSys.spawnSpaceObjectsForPlanets === 'function') {
                            try { remoteSys.spawnSpaceObjectsForPlanets(); } catch (e) { /* non-fatal */ }
                        }
                        // Note: we do not forcibly link a remote object's runtime ref here unless
                        // the player is actually in that system (currentSystem === remoteSys). The
                        // main goal is to ensure the remote system populated its spaceObjects so
                        // the persisted id can be found when the player enters that system.
                    }
                }
            } catch (e) { /* ignore remote spawn attempts */ }

            if (!this._targetObjectRef && this.targetObjectId) {
                // First try current system
                if (currentSystem && Array.isArray(currentSystem.spaceObjects)) {
                    const so = currentSystem.spaceObjects.find(o => o && o.id === this.targetObjectId);
                    if (so) {
                        Object.defineProperty(this, '_targetObjectRef', { value: so, writable: true, enumerable: false, configurable: true });
                    }
                }
                // If still not found, search entire galaxy for the object (covers moved/remote cases)
                if (!this._targetObjectRef && (typeof galaxy !== 'undefined') && Array.isArray(galaxy.systems)) {
                    for (let si = 0; si < galaxy.systems.length; si++) {
                        const sys = galaxy.systems[si];
                        if (!sys || !Array.isArray(sys.spaceObjects)) continue;
                        const found = sys.spaceObjects.find(o => o && o.id === this.targetObjectId);
                        if (found) {
                            Object.defineProperty(this, '_targetObjectRef', { value: found, writable: true, enumerable: false, configurable: true });
                            break;
                        }
                    }
                }
            }
        } catch (e) { /* non-fatal */ }

        // Additional sabotage fallback: if this is a sabotage mission and we still
        // don't have a runtime link, try to ensure the system has decorative objects
        // spawned, attempt to relink by proximity/name, and as a last resort create
        // a mission-specific `SpaceObject` so the mission has a concrete target.
        try {
            if (this.type === MISSION_TYPE.SABOTAGE && !this._targetObjectRef && currentSystem) {
                // Ensure static objects are populated (no-op if already done)
                if (typeof currentSystem.spawnSpaceObjectsForPlanets === 'function') {
                    try { currentSystem.spawnSpaceObjectsForPlanets(); } catch (e) { /* ignore */ }
                }

                // Re-attempt linking by persisted id (in case spawn populated it)
                try {
                    if (this.targetObjectId && Array.isArray(currentSystem.spaceObjects)) {
                        const so2 = currentSystem.spaceObjects.find(o => o && o.id === this.targetObjectId);
                        if (so2) {
                            Object.defineProperty(this, '_targetObjectRef', { value: so2, writable: true, enumerable: false, configurable: true });
                            return;
                        }
                    }
                } catch (e) { /* ignore */ }

                // Try to find a nearby object by matching display name and planet proximity
                try {
                    if (Array.isArray(currentSystem.spaceObjects) && this.targetObjectType && this.targetPlanetName && Array.isArray(currentSystem.planets)) {
                        const planet = currentSystem.planets.find(p => p && p.name === this.targetPlanetName);
                        if (planet && planet.pos) {
                            let best = null; let bestDist = Infinity;
                            const maxConsiderDist = Math.max((planet.size || 0) * 1.2, 600);
                            for (let so of currentSystem.spaceObjects) {
                                if (!so || !so.pos) continue;
                                // Prefer objects whose display name matches the expected type
                                let nameMatch = false;
                                try { nameMatch = (so.getDisplayName && so.getDisplayName() === this.targetObjectType); } catch (e) { nameMatch = false; }
                                const dx = so.pos.x - planet.pos.x;
                                const dy = so.pos.y - planet.pos.y;
                                const d = Math.sqrt(dx * dx + dy * dy);
                                if (d <= maxConsiderDist && d < bestDist) {
                                    // prefer name matches over generic proximity
                                    if (!best || nameMatch || (!best.nameMatch && d < bestDist)) {
                                        best = so; bestDist = d; best.nameMatch = nameMatch;
                                    }
                                }
                            }
                            if (best) {
                                try { this.targetObjectId = best.id || this.targetObjectId; } catch (e) { }
                                Object.defineProperty(this, '_targetObjectRef', { value: best, writable: true, enumerable: false, configurable: true });
                                return;
                            }
                        }
                    }
                } catch (e) { /* ignore proximity match errors */ }

                // Last resort: create a mission-specific SpaceObject so the mission is resolvable
                try {
                    if (typeof SpaceObject === 'function') {
                        // Determine spawn position: near player if present, otherwise near the named planet if available
                        let sx = 0, sy = 0;
                        const planet = (Array.isArray(currentSystem.planets) && this.targetPlanetName) ? currentSystem.planets.find(p => p && p.name === this.targetPlanetName) : null;
                        if (typeof player !== 'undefined' && player && player.pos) {
                            const angle = (typeof random === 'function') ? random(TWO_PI) : (Math.random() * Math.PI * 2);
                            const dist = 600 + ((planet && planet.size) ? Math.max(planet.size, 200) : 800);
                            sx = player.pos.x + (Math.cos(angle) * dist);
                            sy = player.pos.y + (Math.sin(angle) * dist);
                        } else if (planet && planet.pos) {
                            sx = planet.pos.x + 800; sy = planet.pos.y + 120;
                        } else {
                            // Fallback to origin of system
                            sx = 0; sy = 0;
                        }
                        const soNew = new SpaceObject(sx, sy, this.targetObjectType || 'satellite');
                        soNew.isMissionSpecific = true;
                        currentSystem.spaceObjects = currentSystem.spaceObjects || [];
                        currentSystem.spaceObjects.push(soNew);
                        try { this.targetObjectId = soNew.id; } catch (e) { /* ignore */ }
                        Object.defineProperty(this, '_targetObjectRef', { value: soNew, writable: true, enumerable: false, configurable: true });
                        if (typeof uiManager !== 'undefined' && uiManager && typeof uiManager.addMessage === 'function') uiManager.addMessage('Mission target established for sabotage operation.');
                    }
                } catch (e) { /* creating SpaceObject failed — non-fatal */ }
            }
        } catch (e) { /* non-fatal overall */ }
    }

    /**
     * Cleanup runtime references for assassination mission: clear guard principals and null refs.
     */
    _cleanupAssassinationRuntime(currentSystem) {
        try {
            // Clear guard principals so guards revert to normal AI
            if (Array.isArray(this._guardRefs)) {
                for (let guard of this._guardRefs) {
                    try { if (guard) { guard.principal = null; guard.isAssassinationGuard = false; } } catch (e) { }
                }
            }
            // Optionally remove guards from system? We will not remove them automatically to avoid surprising the world state.
            // Clear runtime refs
            try { Object.defineProperty(this, '_targetEnemyRef', { value: null, writable: true, enumerable: false, configurable: true }); } catch (e) { this._targetEnemyRef = null; }
            try { this._guardRefs.length = 0; } catch (e) { this._guardRefs = []; }
            // Clear persisted ids as mission is finished
            this._targetEnemyId = null;
            this._guardIds = [];
        } catch (e) { MISSION_LOG('Error during assassination runtime cleanup:', e); }
    }

    /**
     * Marks the mission as completed, adds reward to player. Called by Player.completeMission.
     * @param {Player} player - Reference to the player object to add credits to.
     */
    complete(player) {
        // Note: Player.completeMission should ideally check if conditions are met before calling this.
        // This method primarily handles the reward and status change.
        MISSION_LOG(`   Mission.complete() called for: ${this.title}`);
        if (player && typeof player.addCredits === 'function') {
            MISSION_LOG(`      -> Granting reward: ${this.rewardCredits} Credits`);
            player.addCredits(this.rewardCredits);
            this.status = 'Completed'; // Mark as completed
            // Record completion in player's personal log when mission completes via Mission.complete()
            try {
                if (typeof player.recordMissionCompletion === 'function') {
                    player.recordMissionCompletion(this);
                }
                if (typeof uiManager !== 'undefined' && uiManager) {
                    uiManager.inactiveMissionIds = uiManager.inactiveMissionIds || new Set();
                    try { uiManager.inactiveMissionIds.add(this.id); } catch (e) { /* ignore */ }
                    uiManager.addMessage(`Mission Complete: ${this.title} | Reward: ${this.rewardCredits}cr`);
                }
                if (typeof saveGame === 'function') saveGame();
            } catch (e) { MISSION_LOG('Error recording mission completion in Mission.complete():', e); }
            // Apply consequences for illegal assassinations (mark player wanted locally)
            try {
                if (this.isIllegal) {
                    const enemy = this._targetEnemyRef || null;
                    let wantedLevel = 1;
                    if (enemy && typeof enemy.role !== 'undefined') {
                        if (enemy.role === (typeof AI_ROLE !== 'undefined' ? AI_ROLE.POLICE : 'POLICE')) wantedLevel = 3;
                        else if (enemy.role === (typeof AI_ROLE !== 'undefined' ? AI_ROLE.HAULER : 'HAULER')) wantedLevel = 2;
                    }
                    if (player && player.currentSystem && typeof player.currentSystem.setPlayerWanted === 'function') {
                        player.currentSystem.setPlayerWanted(true, wantedLevel, 60); // 60s wanted duration
                        if (typeof uiManager !== 'undefined') uiManager.addMessage('WANTED: Authorities alerted by this assassination!', '#ff4444');
                    } else if (player) {
                        // Fallback flag
                        player.isWanted = true;
                        if (typeof uiManager !== 'undefined') uiManager.addMessage('WANTED: Authorities alerted!', '#ff4444');
                    }
                }
            } catch (e) { MISSION_LOG('Error applying illegal-consequence in Mission.complete():', e); }
            // Cleanup runtime refs (guards/principal) after awarding reward
            try { this._cleanupAssassinationRuntime(player?.currentSystem); } catch (e) { MISSION_LOG('Cleanup in complete() failed:', e); }
        } else {
            console.error("Mission.complete() called without valid player object or addCredits method!");
        }
    }

    /** Marks the mission as failed. Called potentially by Player.abandonMission or time limits. */
    fail() {
        MISSION_LOG(`Mission Failed: ${this.title}`);
        this.status = 'Failed';
        // Cleanup runtime refs when mission fails
        try { this._cleanupAssassinationRuntime(null); } catch (e) { MISSION_LOG('Cleanup in fail() failed:', e); }
        // TODO: Add penalties (credits, rep) or consequences later
    }

    /**
     * Updates the progress of the mission (e.g., kills, cargo delivered).
     * @param {number} amount - Amount to increment progress by (default 1).
     */
    updateProgress(amount = 1) {
        if (this.status !== 'Active') return;

        this.progressCount += amount;

        // Check if progress meets target
        if (this.targetCount > 0 && this.progressCount >= this.targetCount) {
            // Can optionally auto-complete or mark as ready
            // For now, just ensuring progress is tracked
            this.status = 'Completable'; // Or keep Active but ready? Let's say Active but capable of complete.
            // Some systems might auto-complete.
            if (typeof uiManager !== 'undefined') {
                uiManager.addMessage(`Mission Objective Updated: ${this.progressCount}/${this.targetCount}`);
            }
        }
    }

    // Update the getSummary method
    /** Returns a short summary string for display on the mission board list. */
    getSummary() {
        // Add status information to the summary for completed/failed missions
        let statusPrefix = '';
        if (this.status === 'Completed') {
            statusPrefix = '[COMPLETED] ';
        } else if (this.status === 'Failed') {
            statusPrefix = '[FAILED] ';
        }

        // Show progress for active bounty missions
        let progressInfo = '';
        if (this.status === 'Active' &&
            (this.type === MISSION_TYPE.BOUNTY_PIRATE || this.type === MISSION_TYPE.BOUNTY_POLICE ||
                this.type === MISSION_TYPE.BOUNTY_ALIEN) &&
            this.progressCount > 0) {
            progressInfo = ` (${this.progressCount}/${this.targetCount})`;
        }

        // Include named target for assassination missions
        if (this.type === MISSION_TYPE.ASSASSINATION && this.targetName) {
            return `${statusPrefix}${this.title} - ${this.rewardCredits}cr`;
        }
        // Summary for sabotage missions — avoid repeating location here (details show Location)
        if (this.type === MISSION_TYPE.SABOTAGE) {
            const obj = this.targetObjectType || 'Strategic Object';
            const factionInfo = this.offeringFaction ? ` (${this.offeringFaction})` : '';
            return `${statusPrefix}${this.title} - ${this.rewardCredits}cr`;
        }
        // Basic summary with status prefix
        return `${statusPrefix}${this.title}${progressInfo} - ${this.rewardCredits}cr`;
    }

    /** Returns a detailed multi-line string for the mission details panel. */
    getDetails() {
        // Standardized details layout for all mission types.
        let details = `Title: ${this.title}\n--------------------\n`;
        details += `Status: ${this.status}\n\n`;

        // Core metadata
        details += `Type: ${this.type}\n`;
        details += `Origin: ${this.originStation} (${this.originSystem})\n`;

        // Determine a single, consistent Location field for all mission types
        const desc = this.description || '';
        let locationStr = 'N/A';
        if (this.type === MISSION_TYPE.SABOTAGE) {
            if (this.targetPlanetName) locationStr = `Near ${this.targetPlanetName} in ${this.destinationSystem || 'the target system'}`;
            else if (this.destinationSystem) locationStr = `${this.destinationSystem}`;
        } else if (this.destinationSystem) {
            locationStr = `${this.destinationStation || 'System Wide'} (${this.destinationSystem})`;
        } else if (this.type === MISSION_TYPE.BOUNTY_PIRATE || this.type === MISSION_TYPE.BOUNTY_POLICE || this.type === MISSION_TYPE.BOUNTY_ALIEN) {
            locationStr = 'Any System';
        } else if (this.type === MISSION_TYPE.ASSASSINATION && this.destinationSystem) {
            locationStr = `${this.destinationStation || 'System Wide'} (${this.destinationSystem})`;
        }
        details += `Location: ${locationStr}\n`;

        // Objective summary (single, consistent label)
        if (this.type === MISSION_TYPE.DELIVERY_LEGAL || this.type === MISSION_TYPE.DELIVERY_ILLEGAL) {
            if (this.cargoType) details += `Objective: Deliver ${this.cargoQuantity}t ${this.cargoType}\n`;
        } else if (this.type === MISSION_TYPE.BOUNTY_PIRATE || this.type === MISSION_TYPE.BOUNTY_POLICE || this.type === MISSION_TYPE.BOUNTY_ALIEN) {
            if (this.targetDesc) details += `Objective: ${this.targetDesc}\n`;
        } else if (this.type === MISSION_TYPE.ASSASSINATION) {
            if (this.targetName) details += `Objective: Eliminate ${this.targetName}\n`;
            else details += `Objective: Eliminate designated target\n`;
        } else if (this.type === MISSION_TYPE.SABOTAGE) {
            const hasGeneratedObjective = desc.indexOf('Sabotage Objective:') !== -1 || desc.indexOf('Objective: Destroy') !== -1 || desc.toLowerCase().includes('destroy');
            if (!hasGeneratedObjective) details += `Objective: Destroy ${this.targetObjectType || 'Strategic Object'}\n`;
        }

        // Reward (single line)
        if (this.type === MISSION_TYPE.SABOTAGE) details += `Reward (High): ${this.rewardCredits} Credits\n`;
        else details += `Reward: ${this.rewardCredits} Credits\n`;

        // Description / Background
        if (this.description) {
            if (this.type === MISSION_TYPE.SABOTAGE) details += `\n${this.description}\n`;
            else details += `\n${this.description}\n\n`;
        }

        // Supplemental fields per type
        if (this.type === MISSION_TYPE.ASSASSINATION) {
            if (this.targetName) details += `Named Target: ${this.targetName}\n`;
            if (this.targetShipType) details += `Target Ship: ${this.targetShipType}\n`;
        }

        if (this.type === MISSION_TYPE.SABOTAGE) {
            if (this.offeringFaction) details += `Offered By: ${this.offeringFaction}\n`;
            if (this.targetFaction) details += `Target Faction: ${this.targetFaction}\n`;
        }

        // Fallback cargo info (if not presented as the objective)
        if (this.cargoType && (this.type !== MISSION_TYPE.DELIVERY_LEGAL && this.type !== MISSION_TYPE.DELIVERY_ILLEGAL)) {
            details += `Cargo: ${this.cargoQuantity}t ${this.cargoType}\n`;
        }

        // Common warnings & meta
        if (this.isIllegal) details += `\n!! This mission involves illegal activity.\n`;
        if (this.timeLimit) details += `Time Limit: ${this.timeLimit} seconds\n`;
        if (this.requiredRep) details += `Requires Reputation: ${this.requiredRep}\n`;

        // Progress for kill/collect missions
        if ((this.type === MISSION_TYPE.BOUNTY_PIRATE || this.type === MISSION_TYPE.BOUNTY_POLICE || this.type === MISSION_TYPE.BOUNTY_ALIEN) && this.progressCount > 0) {
            details += `Progress: ${this.progressCount}/${this.targetCount}\n`;
        }

        return details;
    }
    /**
     * Serializes the mission to a JSON-compatible object.
     * Excludes runtime references like _targetEnemyRef and _guardRefs.
     */
    toJSON() {
        return {
            id: this.id,
            title: this.title,
            type: this.type,
            description: this.description,
            originSystem: this.originSystem,
            originStation: this.originStation,
            destinationSystem: this.destinationSystem,
            destinationStation: this.destinationStation,
            destinationSystemIndex: this.destinationSystemIndex,
            targetCount: this.targetCount,
            targetName: this.targetName,
            targetShipType: this.targetShipType,
            guardCount: this.guardCount,
            guardShipType: this.guardShipType,
            cargoType: this.cargoType,
            cargoQuantity: this.cargoQuantity,
            rewardCredits: this.rewardCredits,
            isIllegal: this.isIllegal,
            requiredRep: this.requiredRep,
            timeLimit: this.timeLimit,
            canLeaveSystem: this.canLeaveSystem,
            _targetEnemyId: this._targetEnemyId,
            _guardIds: this._guardIds,
            offeringFaction: this.offeringFaction,
            targetFaction: this.targetFaction,
            targetObjectType: this.targetObjectType,
            targetObjectId: this.targetObjectId,
            targetPlanetName: this.targetPlanetName,
            spawnSystemIndex: this.spawnSystemIndex,
            status: this.status,
            progressCount: this.progressCount
        };
    }

    /**
     * Creates a new Mission instance from a JSON object.
     * @param {Object} json - The JSON object to deserialize.
     * @returns {Mission} The rehydrated Mission object.
     */
    static fromJSON(json) {
        return new Mission(json);
    }
} // End of Mission Class