// ****** surfaceTerrain.js ******
// Terrain generation and rendering for surface mode
// Extracted from surfaceMode.js for better maintainability

/**
 * SurfaceTerrain - Handles terrain mesh generation, height sampling, and rendering
 * 
 * Uses Perlin noise to generate a height-mapped terrain mesh that is rendered
 * to an off-screen buffer for performance. The terrain follows the player
 * and regenerates when they move to a new grid cell.
 */
class SurfaceTerrain {
    /**
     * @param {Object} config - SURFACE_CONFIG object with terrain settings
     */
    constructor(config) {
        this.config = config;

        // Double buffering for smooth transitions
        this.currentBuffer = null;
        this.currentGridX = null;
        this.currentGridY = null;

        // Next buffer being generated by worker
        this.pendingBuffer = null;
        this.isGenerating = false;

        // No transition - instant swap approach
        this.lastSwapTime = 0;
        this.minSwapInterval = 100; // ms minimum between swaps

        // Worker instance
        this.worker = null;
        this._initWorker();

        // Planet reference for palette and feature seed
        this.planet = null;

        // Performance: Height sampling cache (cleared each frame)
        this.heightCache = new Map();
        this.heightCacheFrame = -1;
    }

    _initWorker() {
        if (this.worker) return;

        try {
            this.worker = new Worker('surface_worker.js');
            this.worker.onmessage = this._handleWorkerMessage.bind(this);
            console.log("SurfaceTerrain worker initialized");
        } catch (e) {
            console.error("Failed to initialize SurfaceTerrain worker:", e);
        }
    }

    _handleWorkerMessage(e) {
        const data = e.data;
        if (data.bitmap) {
            // We received a new texture
            this.pendingBuffer = {
                bitmap: data.bitmap,
                gridX: data.gridX,
                gridY: data.gridY
            };
            this.isGenerating = false;
            // Note: We don't verify if it's "stale" here because even an old buffer 
            // is better than nothing, but in practice the request flow controls this.
        }
    }

    /**
     * Set the planet for terrain generation
     * @param {Object} planet - Planet object with palette and featureRand
     */
    setPlanet(planet) {
        this.planet = planet;
        // Reset buffers on planet change
        this.currentBuffer = null;
        this.currentGridX = null;
        this.currentGridY = null;
        this.pendingBuffer = null;
        this.isGenerating = false;
        this.lastSwapTime = 0;

        // Ensure worker is alive (it might have been terminated on cleanup)
        if (!this.worker) {
            this._initWorker();
        }
    }

    /**
     * Create the offscreen buffer for terrain rendering
     * (Legacy signature compat - mainly just clears buffers here)
     */
    createBuffer(screenWidth, screenHeight) {
        // No-op for worker-based approach as buffer is created in worker
        // But we can reset state here
        this.currentBuffer = null;
    }

    /**
     * Clean up the terrain buffer and worker
     */
    cleanup() {
        if (this.currentBuffer && typeof this.currentBuffer.close === 'function') this.currentBuffer.close();
        if (this.pendingBuffer && this.pendingBuffer.bitmap && typeof this.pendingBuffer.bitmap.close === 'function') this.pendingBuffer.bitmap.close();
        this.currentBuffer = null;
        this.pendingBuffer = null;

        if (this.worker) {
            this.worker.terminate();
            this.worker = null;
        }
        this.heightCache.clear();
    }

    /**
     * Get terrain feature random seed with fallback
     * @returns {number} Feature seed for noise generation
     * @private
     */
    _getFeatureRand() {
        return this.planet?.featureRand ?? this.config.DEFAULT_FEATURE_SEED;
    }

    /**
     * Get terrain height at a specific world position
     * Uses same noise logic as worker but runs on main thread for collisions/physics
     */
    getHeightAt(worldX, worldY) {
        if (!this.planet) return 0;

        // Check if p5.js noise function is available
        if (typeof noise !== 'function') {
            return 0;
        }

        // Performance: Clear cache each frame and use cached values
        if (typeof frameCount !== 'undefined' && frameCount !== this.heightCacheFrame) {
            this.heightCache.clear();
            this.heightCacheFrame = frameCount;
        }

        // Use integer grid key for cache (reduces cache misses from floating point)
        const key = `${Math.floor(worldX / 10)},${Math.floor(worldY / 10)}`;
        if (this.heightCache.has(key)) {
            return this.heightCache.get(key);
        }

        const featureRand = this._getFeatureRand();
        const sampleMultiplier = 0.003;

        const nx = worldX * sampleMultiplier + featureRand * 0.001;
        const ny = worldY * sampleMultiplier + featureRand * 0.002;
        const nz = featureRand * 0.6;

        const noiseVal = noise(nx, ny, nz);
        const height = noiseVal * 500; // 0-500 range (no negative terrain)

        this.heightCache.set(key, height);
        return height;
    }

    /**
     * Update terrain: Check player position and request new buffer if needed
     * @param {number} playerX 
     * @param {number} playerY 
     * @param {boolean} forceRequest - force a worker request (e.g. on teleport/entry)
     * @returns {boolean} True if a NEW buffer was swapped in this frame (changed)
     */
    update(playerX, playerY, forceRequest = false, sunAngle = -Math.PI / 4) {
        if (!this.planet || !this.worker) return false;

        const cellSize = this.config.MESH_SIZE / this.config.MESH_RESOLUTION;
        const targetGridX = Math.round(playerX / cellSize);
        const targetGridY = Math.round(playerY / cellSize);
        
        const now = typeof performance !== 'undefined' ? performance.now() : Date.now();

        // 1. Check if pending buffer is ready to be swapped
        let bufferSwapped = false;
        if (this.pendingBuffer) {
            // Enforce minimum time between swaps to prevent rapid buffer changes
            const timeSinceLastSwap = now - this.lastSwapTime;
            if (timeSinceLastSwap >= this.minSwapInterval || !this.currentBuffer) {
                // Close old buffer immediately before swap
                if (this.currentBuffer && typeof this.currentBuffer.close === 'function') {
                    this.currentBuffer.close();
                }

                // Instant swap to new buffer (no alpha transition)
                this.currentBuffer = this.pendingBuffer.bitmap;
                this.currentGridX = this.pendingBuffer.gridX;
                this.currentGridY = this.pendingBuffer.gridY;

                this.pendingBuffer = null;
                this.isGenerating = false;
                this.lastSwapTime = now;
                bufferSwapped = true;
            }
        }

        // 2. Do we need to request a new one?
        // If getting too far from current center
        let dist = 999999;
        if (this.currentGridX !== null) {
            const dx = targetGridX - this.currentGridX;
            const dy = targetGridY - this.currentGridY;
            dist = Math.sqrt(dx * dx + dy * dy);
        }

        // Request new buffer early (when > 5 cells away) to ensure it's ready before we need it
        // The larger buffer size means we can request earlier without visible edges
        if (!this.isGenerating && (forceRequest || this.currentBuffer === null || dist > 5)) {
            this.isGenerating = true;

            // Prepare data for worker
            const planetPalette = this.planet.palette ? this.planet.palette.map(c => c.levels) : null;

            this.worker.postMessage({
                cmd: 'generateMesh',
                gridX: targetGridX,
                gridY: targetGridY,
                meshSize: this.config.MESH_SIZE,
                resolution: this.config.MESH_RESOLUTION,
                planetSeed: (typeof this.planet.seed === 'number' ? this.planet.seed : Math.floor((this.planet.featureRand || 0) * 1000000)) || 12345,
                planetPalette: planetPalette,
                sunAngle: sunAngle,
                extrusionAngle: this.config.EXTRUSION_ANGLE,
                featureRand: this._getFeatureRand()
            });
        }

        return bufferSwapped;
    }

    // Legacy mapping (no longer used directly but kept for compatibility/interface)
    generateMesh() { return false; }
    updateBuffer() { }

    /**
     * Draw the terrain buffer (instant swap, no alpha transitions)
     */
    draw() {
        if (!this.currentBuffer || this.currentGridX === null) return;

        const cellSize = this.config.MESH_SIZE / this.config.MESH_RESOLUTION;

        if (typeof drawingContext !== 'undefined') {
            const ctx = drawingContext;
            
            // Draw current buffer at full opacity (no alpha blending)
            const bufferWorldCX = this.currentGridX * cellSize;
            const bufferWorldCY = this.currentGridY * cellSize;
            const w = this.currentBuffer.width;
            const h = this.currentBuffer.height;
            const bx = bufferWorldCX - w / 2;
            const by = bufferWorldCY - h / 2;
            
            ctx.drawImage(this.currentBuffer, bx, by, w, h);
        }
    }

    /**
     * Get the current effective grid position (center of the texture)
     */
    getGridPosition() {
        return { x: this.currentGridX || 0, y: this.currentGridY || 0 };
    }
}

// Make available globally
if (typeof window !== 'undefined') {
    window.SurfaceTerrain = SurfaceTerrain;
}

console.log("surfaceTerrain.js loaded");
