// ****** missionTypes/SabotageHandler.js ******
// Handler for sabotage missions with target object linking and backstory generation.

/**
 * Handler for SABOTAGE mission type.
 */
class SabotageHandler extends MissionTypeHandler {
    static types = [MISSION_TYPE.SABOTAGE];
    static requiredFaction = null; // Public missions

    // Canonical space object types for sabotage targets
    static CANONICAL_TYPES = [
        'satellite', 'telescope', 'relay', 'habitat', 'debris', 'probe', 'beacon',
        'solarSail', 'engineArray', 'cargoCluster', 'researchArray', 'orbitalGarden',
        'decoyBuoy', 'miningPlatform', 'ancientRelic', 'signalFlare', 'spaceStation',
        'observatoryDome', 'hydroponicsBay', 'weaponPlatform', 'shieldGenerator',
        'energyCollector', 'quantumGate', 'fuelDepot', 'commDish', 'solarFarm',
        'iceCrystal', 'nebulaFragment', 'alienArtifact', 'wreckage', 'asteroidMiner'
    ];

    // Economy to faction name mapping
    static ECONOMY_TO_FACTION = {
        'Agricultural': 'Agricultural Collective',
        'Industrial': 'Industrial Consortium',
        'Mining': 'Mining Syndicate',
        'Refinery': 'Refinery Corporation',
        'Post Human': 'Post Human Council',
        'Tourism': 'Tourism Board',
        'Service': 'Service Guild',
        'Military': 'Military Command',
        'Offworld': 'Offworld Trading Company',
        'Alien': 'Xenological Institute',
        'Separatist': 'Separatist Movement',
        'Imperial': 'Imperial Authority'
    };

    /**
     * Create a sabotage mission.
     * @param {Object} context - Generation context
     * @returns {Mission|null}
     */
    static create(context) {
        const { originSystem, originStation, galaxy, player } = context;

        // Find destination
        const destinationInfo = MissionGenerator.findNearbyDestination(originSystem, galaxy, false, 6);
        if (!destinationInfo?.system) return null;
        const destSystem = destinationInfo.system;

        // Choose a planet (excluding sun at index 0)
        let planetName = 'Outer Orbit';
        try {
            if (Array.isArray(destSystem.planets) && destSystem.planets.length > 1) {
                const idx = Math.floor(random(1, destSystem.planets.length));
                const p = destSystem.planets[idx];
                if (p?.name) planetName = p.name;
            }
        } catch (e) { /* ignore */ }

        // Determine offering faction
        let offeringFaction = originStation?.faction || originSystem?.economyType || null;
        if (typeof offeringFaction === 'string' && this.ECONOMY_TO_FACTION[offeringFaction]) {
            offeringFaction = this.ECONOMY_TO_FACTION[offeringFaction];
        } else if (typeof offeringFaction !== 'string') {
            const pool = ['Separatist Movement', 'Imperial Authority', 'Military Command'];
            offeringFaction = pool[Math.floor(random(0, pool.length))];
        }

        // Try to bind to actual space object
        let targetObjectType = null;
        let targetObjectId = null;
        ({ targetObjectType, targetObjectId } = this._bindToRealObject(destSystem, planetName));

        // Fallback to canonical type
        if (!targetObjectType) {
            targetObjectType = this._getCanonicalTypeName();
        }

        // Calculate reward
        let jumpDistance = 3;
        try {
            jumpDistance = galaxy.getJumpDistance(originSystem.systemIndex, destSystem.systemIndex);
        } catch (e) { /* use default */ }
        if (!isFinite(jumpDistance) || jumpDistance <= 0) jumpDistance = 3;

        const baseReward = 5000;
        const jumpMultiplier = 2000;
        const reward = Math.floor(baseReward + jumpDistance * jumpMultiplier + random(1000, 5000));

        const jumpText = jumpDistance === 1 ? '1 jump' : `${jumpDistance} jumps`;
        const title = `Sabotage: Destroy ${targetObjectType} near ${planetName} (${jumpText})`;

        return new Mission({
            type: MISSION_TYPE.SABOTAGE,
            title: title,
            description: '', // Generated by _generateBackstory when needed
            originSystem: originSystem.name,
            originStation: originStation.name,
            destinationSystem: destSystem.name,
            spawnSystemIndex: typeof destSystem.systemIndex === 'number' ? destSystem.systemIndex : null,
            systemIndex: typeof destSystem.systemIndex === 'number' ? destSystem.systemIndex : null,
            destinationStation: null,
            targetObjectType: targetObjectType,
            targetObjectId: targetObjectId,
            targetPlanetName: planetName,
            offeringFaction: offeringFaction,
            rewardCredits: reward,
            isIllegal: true,
            progressCount: 0
        });
    }

    /**
     * Try to bind to a real SpaceObject near the planet.
     * @private
     */
    static _bindToRealObject(destSystem, planetName) {
        let targetObjectType = null;
        let targetObjectId = null;

        try {
            // Ensure decorative objects exist
            if ((!Array.isArray(destSystem.spaceObjects) || destSystem.spaceObjects.length === 0) &&
                typeof destSystem.spawnSpaceObjectsForPlanets === 'function') {
                try { destSystem.spawnSpaceObjectsForPlanets(); } catch (e) { /* non-fatal */ }
            }

            if (destSystem?.spaceObjects?.length > 0 && Array.isArray(destSystem.planets)) {
                const planetObj = destSystem.planets.find(p => p?.name === planetName);
                if (planetObj?.pos) {
                    let best = null;
                    let bestDist = Infinity;
                    const maxConsiderDist = Math.max((planetObj.size || 0) * 1.2, 600);

                    for (const so of destSystem.spaceObjects) {
                        if (!so?.pos) continue;
                        const dx = so.pos.x - planetObj.pos.x;
                        const dy = so.pos.y - planetObj.pos.y;
                        const d = Math.sqrt(dx * dx + dy * dy);
                        if (d <= maxConsiderDist && d < bestDist) {
                            best = so;
                            bestDist = d;
                        }
                    }

                    if (best) {
                        targetObjectId = best.id || null;
                        try {
                            targetObjectType = best.getDisplayName ? best.getDisplayName() : (best.type || null);
                        } catch (e) {
                            targetObjectType = best.type || null;
                        }
                    }
                }
            }
        } catch (e) {
            console.warn('SabotageHandler: Failed to bind to real space object', e);
        }

        return { targetObjectType, targetObjectId };
    }

    /**
     * Get a random canonical type display name.
     * @private
     */
    static _getCanonicalTypeName() {
        try {
            if (typeof SpaceObject === 'function') {
                const namePool = this.CANONICAL_TYPES.map(t => {
                    try { return (new SpaceObject(0, 0, t)).getDisplayName(); } catch (e) { return t; }
                }).filter(Boolean);
                if (namePool.length) {
                    return namePool[Math.floor(random(0, namePool.length))];
                }
            }
        } catch (e) { /* fallback */ }
        return this.CANONICAL_TYPES[Math.floor(random(0, this.CANONICAL_TYPES.length))];
    }

    /**
     * Monitor sabotage target state.
     */
    static update(mission, currentSystem) {
        // Try to link target object if needed
        if (!mission._targetObjectRef && mission.targetObjectId && currentSystem?.spaceObjects) {
            const so = currentSystem.spaceObjects.find(o => o?.id === mission.targetObjectId);
            if (so) mission._targetObjectRef = so;
        }

        const targetObj = mission._targetObjectRef;

        // Check if target is destroyed
        if (targetObj?.destroyed) {
            if (typeof player !== 'undefined' && player) {
                mission.complete(player);
                mission._targetObjectRef = null;
                if (player.activeMission === mission) player.activeMission = null;
            }
            return;
        }

        // Galaxy-wide search for target if not found locally
        if (!targetObj && mission.targetObjectId) {
            const foundObj = this._searchGalaxyForTarget(mission);
            if (foundObj === true) return; // Mission completed
            if (foundObj) {
                mission._targetObjectRef = foundObj;
            }
        }
    }

    /**
     * Search galaxy for sabotage target.
     * @private
     */
    static _searchGalaxyForTarget(mission) {
        if (typeof galaxy === 'undefined' || !Array.isArray(galaxy.systems)) return null;

        // Only do full scan when player is in target system
        if (typeof mission.spawnSystemIndex === 'number' &&
            typeof player !== 'undefined' && player?.currentSystem?.index !== mission.spawnSystemIndex) {
            return null;
        }

        for (const sys of galaxy.systems) {
            if (!sys?.spaceObjects) continue;
            const so = sys.spaceObjects.find(o => o?.id === mission.targetObjectId);
            if (so) {
                if (so.destroyed) {
                    mission.complete(player);
                    mission._targetObjectRef = null;
                    if (player?.activeMission === mission) player.activeMission = null;
                    return true;
                }
                return so;
            }
        }

        // Object not found anywhere - assume destroyed
        mission.complete(player);
        mission._targetObjectRef = null;
        if (player?.activeMission === mission) player.activeMission = null;
        return true;
    }

    /**
     * Generate backstory for sabotage mission.
     */
    static generateBackstory(mission) {
        const offer = mission.offeringFaction || 'A local faction';
        const target = this._deriveTargetFaction(offer);
        const obj = mission.targetObjectType || 'strategic installation';

        return this._getSabotageReason(offer.toLowerCase(), offer, target, obj);
    }

    /**
     * Derive opposing faction.
     * @private
     */
    static _deriveTargetFaction(offer) {
        const offerLower = (offer || '').toLowerCase();
        if (offerLower.includes('separat')) return 'Imperial forces';
        if (offerLower.includes('imper')) return 'Separatist rebels';
        if (offerLower.includes('milit')) return 'Alien incursion';
        return 'a rival faction';
    }

    /**
     * Get faction-specific reason for sabotage.
     * @private
     */
    static _getSabotageReason(offerLower, offer, target, obj) {
        const reasons = {
            'separat': `The ${offer} claims the ${obj} is a forward listening post used by ${target} to track convoy movements. Destroying it would blind the occupiers.`,
            'imper': `Agents of the ${offer} have intelligence that the ${obj} is a covert supply hub for ${target}. Removing it would disrupt their logistics.`,
            'milit': `Military analysts suspect the ${obj} has been corrupted by alien tech. ${offer} wants it eliminated before it spreads.`,
            'tourism': `The ${offer} reports the ${obj} is generating hazardous interference endangering passenger ships.`,
            'mining': `The ${offer} claims the ${obj} is disrupting mineral surveys. Its removal would open valuable deposits.`,
            'refinery': `Engineers from the ${offer} report the ${obj} is contaminating fuel processing routes.`,
            'agricultural': `The ${offer} asserts the ${obj} is interfering with agricultural drones.`,
            'service': `The ${offer} indicates the ${obj} is blocking critical emergency frequencies.`,
            'post human': `The ${offer} considers the ${obj} incompatible with human transcendence.`,
            'council': `The ${offer} considers the ${obj} incompatible with human transcendence.`,
            'offworld': `The ${offer} reports the ${obj} is interfering with trade beacon frequencies.`,
            'trading': `The ${offer} reports the ${obj} is interfering with trade beacon frequencies.`,
            'xeno': `The ${offer} has determined the ${obj} poses contamination risk to xenological research.`,
            'alien': `The ${offer} has determined the ${obj} poses contamination risk to xenological research.`,
            'consortium': `The ${offer} reports the ${obj} is damaging manufacturing automation.`,
            'industrial': `The ${offer} reports the ${obj} is damaging manufacturing automation.`
        };

        for (const [key, reason] of Object.entries(reasons)) {
            if (offerLower.includes(key)) return reason;
        }

        return `Intelligence suggests the ${obj} is a critical node for ${target}. Removing it would weaken their presence.`;
    }

    /**
     * Get objective string.
     */
    static getObjective(mission) {
        return `Objective: Destroy ${mission.targetObjectType || 'Strategic Object'}`;
    }

    /**
     * Get supplemental details.
     */
    static getSupplementalDetails(mission) {
        let details = '';
        if (mission.offeringFaction) details += `Offered By: ${mission.offeringFaction}\n`;
        if (mission.targetFaction) details += `Target Faction: ${mission.targetFaction}\n`;
        return details;
    }

    /**
     * Generate news for sabotage completion.
     */
    static generateNews(mission, player) {
        if (typeof GameGlobals === 'undefined' || !GameGlobals.newsManager) return;
        const systemName = player.currentSystem?.name || mission.destinationSystem || 'Unknown';
        try {
            GameGlobals.newsManager.addSabotageNews(mission.targetObjectType, mission.targetPlanetName, systemName);
        } catch (e) {
            MISSION_LOG('Error generating sabotage news:', e);
        }
    }

    static getDisplayColor() {
        return [255, 150, 50]; // Orange for sabotage
    }

    static getIcon() {
        return '💥';
    }
}

// Register with the registry
if (typeof MissionTypeRegistry !== 'undefined') {
    MissionTypeRegistry.register(SabotageHandler);
}

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
    module.exports = SabotageHandler;
    global.SabotageHandler = SabotageHandler;
}
